language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

install:
  - travis_retry composer install --no-interaction

jobs:
  include:
    - stage: Code coverage
      script:
        - ./vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml
