language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer install --no-interaction

jobs:
  include:
    - stage: Coding Standards
      script: vendor/bin/php-cs-fixer fix -v --diff --dry-run

    - stage: Code Coverage
      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml
