# https://docs.github.com/en/actions

name: Build

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  hello:
    name: Hello

    runs-on: ubuntu-latest

    steps:
      - name: Echo a greeting
        run: echo 'Hello, GitHub Actions!'
