# https://docs.github.com/en/actions

name: Build

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  static-analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Determine composer cache directory
        id: determine-composer-cache-directory
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run phpstan/phpstan
        run: vendor/bin/phpstan analyse

  coding-standards:
    name: Coding Standards

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Determine composer cache directory
        id: determine-composer-cache-directory
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run friendsofphp/php-cs-fixer
        run: vendor/bin/php-cs-fixer fix -v --diff --dry-run
